"""extend horse profile (chip, stall, health, feeding, vet) and add vaccinations table

Revision ID: 0a1c4f0ad5a6
Revises: a5de94b4696a
Create Date: 2026-08-08 00:41:35.198322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1c4f0ad5a6'
down_revision = 'a5de94b4696a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('given_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccinations_horse_id'), ['horse_id'], unique=False)

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chip_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stall_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('health_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feeding_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vet_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vet_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('important_alert', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('important_alert')
        batch_op.drop_column('vet_contact')
        batch_op.drop_column('vet_name')
        batch_op.drop_column('feeding_plan')
        batch_op.drop_column('allergies')
        batch_op.drop_column('health_notes')
        batch_op.drop_column('stall_number')
        batch_op.drop_column('chip_number')

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccinations_horse_id'))

    op.drop_table('vaccinations')
    # ### end Alembic commands ###
