"""add daily_reports table (normal/abnormal daily report system)

Revision ID: 2183ce478c90
Revises: ddc9e4a868d2
Create Date: 2026-08-08 01:44:21.939660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2183ce478c90'
down_revision = 'ddc9e4a868d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('appetite_status', sa.String(length=10), nullable=True),
    sa.Column('appetite_detail', sa.String(length=500), nullable=True),
    sa.Column('water_status', sa.String(length=10), nullable=True),
    sa.Column('water_detail', sa.String(length=500), nullable=True),
    sa.Column('droppings_status', sa.String(length=10), nullable=True),
    sa.Column('droppings_detail', sa.String(length=500), nullable=True),
    sa.Column('behavior_status', sa.String(length=10), nullable=True),
    sa.Column('behavior_detail', sa.String(length=500), nullable=True),
    sa.Column('movement_status', sa.String(length=10), nullable=True),
    sa.Column('movement_detail', sa.String(length=500), nullable=True),
    sa.Column('training_activity', sa.Text(), nullable=True),
    sa.Column('medication_given', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horse_id', 'report_date', name='uq_daily_report_horse_date')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_horse_id'))

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
