"""add daily_tasks table for structured task workflow

Revision ID: 2ad1a6706b0c
Revises: 95068a1bdb13
Create Date: 2026-08-04 15:22:20.249364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad1a6706b0c'
down_revision = '95068a1bdb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horse_id', 'task_date', 'task_type', name='uq_daily_task_horse_date_type')
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_tasks_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_task_date'), ['task_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_daily_tasks_task_date'))
        batch_op.drop_index(batch_op.f('ix_daily_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_daily_tasks_horse_id'))

    op.drop_table('daily_tasks')
    # ### end Alembic commands ###
