"""add horse pedigree/gender fields and user terms acceptance

Revision ID: 462ff16248fe
Revises: c4eacaf1ba0c
Create Date: 2026-08-06 13:47:29.223096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ff16248fe'
down_revision = 'c4eacaf1ba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sire_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dam_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_at')

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('dam_name')
        batch_op.drop_column('sire_name')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
