"""add stable approval status (pending/approved/rejected)

Revision ID: 49ddcd4776dc
Revises: 3b1f449dee1c
Create Date: 2026-08-08 03:49:51.794119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ddcd4776dc'
down_revision = '3b1f449dee1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stables', schema=None) as batch_op:
        # مهم جدًا: server_default='approved' هنا يضمن أن كل المرابط الحية الموجودة فعليًا على
        # الإنتاج (اللي كانت تعمل بدون أي مفهوم "اعتماد" من قبل) تبقى ظاهرة وتعمل بدون انقطاع —
        # لولا هذا، كانت ستتحول تلقائيًا لحالة "pending" (الافتراضي بالنموذج) وتختفي فورًا عن
        # الزوار فور تطبيق هذا الترحيل. حالة "pending" الافتراضية الجديدة تنطبق فقط على التسجيلات
        # الذاتية الجديدة من الآن فصاعدًا (تُمرَّر صراحة بالكود عند الإنشاء)، لا على البيانات القديمة.
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False,
                                       server_default='approved'))
        batch_op.create_index(batch_op.f('ix_stables_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stables_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
