"""make review booking_id unique to prevent duplicate reviews

Revision ID: 4aca7898dd2d
Revises: ac4e237c8fed
Create Date: 2026-08-06 08:36:12.497953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aca7898dd2d'
down_revision = 'ac4e237c8fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reviews_booking_id', ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_booking_id', type_='unique')

    # ### end Alembic commands ###
