"""initial schema

Revision ID: 75554485afaf
Revises: 
Create Date: 2026-08-03 10:30:55.040634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75554485afaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_label', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stable_id'), ['stable_id'], unique=False)

    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('service_type', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horses_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_horses_stable_id'), ['stable_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('sessions_remaining', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_stable_id'), ['stable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('feeding', sa.Text(), nullable=True),
    sa.Column('care', sa.Text(), nullable=True),
    sa.Column('training', sa.Text(), nullable=True),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_log_date'), ['log_date'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('experience_rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_log_date'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_horse_id'))

    op.drop_table('daily_logs')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_stable_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horses_stable_id'))
        batch_op.drop_index(batch_op.f('ix_horses_service_type'))
        batch_op.drop_index(batch_op.f('ix_horses_owner_id'))

    op.drop_table('horses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stable_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('packages')
    op.drop_table('stables')
    # ### end Alembic commands ###
