"""add staff role, specialty, and task staff assignment

Revision ID: 8c9006d44af5
Revises: 2ad1a6706b0c
Create Date: 2026-08-04 15:33:22.212827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9006d44af5'
down_revision = '2ad1a6706b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_daily_tasks_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_tasks_assigned_to_id_users', type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    # ### end Alembic commands ###
