"""add achievements table for lounge feature

Revision ID: 95068a1bdb13
Revises: 75554485afaf
Create Date: 2026-08-03 19:46:22.049562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95068a1bdb13'
down_revision = '75554485afaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('competition_name', sa.String(length=200), nullable=True),
    sa.Column('achievement_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_stable_id'), ['stable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_status'))
        batch_op.drop_index(batch_op.f('ix_achievements_stable_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_horse_id'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
