"""add horse is_public visibility toggle

Revision ID: a5de94b4696a
Revises: 462ff16248fe
Create Date: 2026-08-07 23:11:13.976905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5de94b4696a'
down_revision = '462ff16248fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    # نُبقي server_default بدون إزالته لاحقًا؛ يضمن هذا أن أي صف حالي يُعبَّأ تلقائيًا بـ True
    # (كل الخيول ظاهرة افتراضيًا) قبل ما يتحكم مالك الإسطبل بإخفاء ما يشاء لاحقًا.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
