"""add stable city/coordinates and gallery photos

Revision ID: ac4e237c8fed
Revises: 8c9006d44af5
Create Date: 2026-08-05 10:55:13.417899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4e237c8fed'
down_revision = '8c9006d44af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stable_id'], ['stables.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_photos_stable_id'), ['stable_id'], unique=False)

    with op.batch_alter_table('stables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stables_city'), ['city'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stables_city'))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('city')

    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_photos_stable_id'))

    op.drop_table('gallery_photos')
    # ### end Alembic commands ###
